baseurl: "" 
url: "https://turtlecoin.lol"

# Do not copy these files to the build folder
exclude:
 - Gemfile
 - Gemfile.lock
 - scripts
 - Rakefile
 - README.md
 - .bundle
 - vendor

gems:
 - jekyll-multiple-languages-plugin

# Localization config

languages: ["en", "de", "es", "fr", "he", "pt-br", "tr", "zh"]

language_names:
  en:
    short: en
    full: English
  de:
    short: de
    full: Deutsch
  es:
    short: es
    full: Espa√±ol
  fr:
    short: fr
    full: French
  he:
    short: he
    full: Hebrew
  pt-br:
    short: pt-br
    full: Portuguese
  tr:
    short: tr
    full: Turkish
  zh:
    short: zh
    full: Chinese
  # dev:
  #   short: dev
  #   full: Development


# couldn't make this work 
# exclude_from_localizations: ["assets"]
